'''
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''

class Solution(object):
    def findTheDifferenceBT(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        O(st) where s, t is len of s, t
        """
        # convert string to list 
        sList = [char for char in s] # O(s) with s is length of s
        for char in t: # O(t)
            if char not in sList: # O(s)
                return char
            sList.pop(sList.index(char)) # remove the item from sList, sList length will reduce 1 by each t iteration
        
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        O(st) where s, t is len of s, t
        """
        for char in t:
            if char not in s or t.count(char) > s.count(char):
                return char

    def findTheDifferenceXOR(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        ch = 0
        
        for char in s:
            ch ^= ord(char)
            print(char, format(ord(char), 'b'))
            print(char, ord(char), ch)
            
        for char in t:
            ch ^= ord(char)
            print(char,ord(char), ch)
        return chr(ch)

s = "abcd"
t = "abcde"

sol = Solution()
print(sol.findTheDifferenceXOR(s,t))